basefiles:
    commodity: ../common/commodities.json
    contract: ../common/contracts.json
    holiday: ../common/holidays.json
    hot: ../common/hots.json
    session: ../common/sessions.json
bspolicy: actpolicy.yaml
data:
    store:
        path: ../FUT_Data/
env:
    fees: ../common/fees.json
    filters: filters.yaml
    mode: product
    name: hft
    product:
        session: TRADING
executers:
-   active: false
    id: exe1
    policy:
        default:
            name: WtExeFact.WtSimpExeUnit
    scale: 1
    trader: simnow
parsers: tdparsers.yaml
traders: tdtraders.yaml
